language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: WD45ZI3SWMRKY64Qs5OSmc0RypkDBgoMe6C3M1jYzWTaBtSzuQpjGfQx6koFUEZrbhVM9SWwHbQYs0cwXU1bPRr4XZXrvh7yHe9fB3a6GejhJJzSQvJIkZY+rAn0Jie1UV9n4JSO7+NhDVxGLEo3HpW7S53ARmFaV2XoPYLTZJ8cbG2IiaYxnVt/IdxAJGVpGu/EIzFJITNlsXnTFayegLOiPFBbXRBnr+UmHWLjs3DhErjQVdBBJ9h2wx3zNJTfBfuN2v6JlJceGUQ54iWu10K6LatQD+TNx4JwMJhuwKdnP+PKzxV7rIoyIIyPAt+eVO1AgrDpGhoYEbbd7ikQiUnl9hNcVDGJ4HQmrdo6KlJi7VIMpoP8qllXvqqi13Wbz/JMDrQk8ZDe8ogHkM3JmkPOeKz+v3MF8LC4hWHIt93LQjFJ1wHnahBUKrkjbEtpguATYIdwGWxUulliQ6/6Ik73dyql4pZGp+4H9mxspTVut4by3iHHTO3CWfSXeNs9PMFEHcsyQscT247eWxMGHT4QVMKGVm+LMKmhSh/zJx0e6AGrP06LjoXQ7SOgAvfOIKsfCzXGdRjqGn40OrZj1IP8u7IXPoiYKNULSFQzrR6IVMc9nKgMc9UvbbdVvDp/dL7LAVLfEcBPmvq3q6smg/WjKNuqTHnUNS8S29VyMC8=
  app: radiant-lake-39661
  on:
    repo: dysol/my-api-server
